name: CodsPerms
main: com.codisimus.plugins.codsperms.CodsPerms
version: 0.3.0
author: Codisimus
website: www.codisimus.com
softdepend: [DatabaseAPI]
commands:
  perm:
    description: Used to set permissions in-game
    usage: /<command> help
    aliases: [permission, perms, p]
    permission: permissions.manage
permissions:
  permissions.manage:
    description: Needed to set permissions